id: e7a2a7b36dc54d56af46981d0d728beb
initial_creation_type: ocr
created_at: 12/11/2021
last_modified_at: 26/11/2021
source_metadata:
  id: bdr:W22084
  title: བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
  volumes:
    5ccd2420d5de40c7973e22d6192d0bd4:
      image_group_id: I0886
      title: ''
      base_file: v001.txt
    2a308959bde748dfb207a397a5065de5:
      image_group_id: I0887
      title: ''
      base_file: v002.txt
    47b2d1ead3534f17855305e354b130ee:
      image_group_id: I0888
      title: ''
      base_file: v003.txt
    0eca30fcb90f40e5a22c762e8cbb7d76:
      image_group_id: I0889
      title: ''
      base_file: v004.txt
    2aa8e8d30cb54f3abac3bfa87eedce8d:
      image_group_id: I0890
      title: ''
      base_file: v005.txt
    2226bdae74c549238d1788bf0b272d4e:
      image_group_id: I0891
      title: ''
      base_file: v006.txt
    52917a9bec5942d3a7701321ce24c7ea:
      image_group_id: I0892
      title: ''
      base_file: v007.txt
    6db8a5c7b7ba48ac9a28908a09a10eb0:
      image_group_id: I0893
      title: ''
      base_file: v008.txt
    c75680c67fa54855a858a9ceb66ecdc7:
      image_group_id: I0894
      title: ''
      base_file: v009.txt
    2f551edfa5a94ee38abc13a37585d728:
      image_group_id: I0895
      title: ''
      base_file: v010.txt
    90ae89333e83459cb4ea3d5d88ac08a4:
      image_group_id: I0896
      title: ''
      base_file: v011.txt
    586772b918ea4fd3a1037343eb69ad37:
      image_group_id: I0897
      title: ''
      base_file: v012.txt
    514effde5e8844728f267c900b03e293:
      image_group_id: I0898
      title: ''
      base_file: v013.txt
    c29a1bea999742ac83208c88a27dbf7a:
      image_group_id: I0899
      title: ''
      base_file: v014.txt
    cee93ef368b643d6bb758f65c67b9bd8:
      image_group_id: I0900
      title: ''
      base_file: v015.txt
    5c3d9566da0b483b9ff3b95fd81add87:
      image_group_id: I0901
      title: ''
      base_file: v016.txt
    a2bfd9139f4249c78c1d130122818902:
      image_group_id: I0902
      title: ''
      base_file: v017.txt
    8903dba766354d70874f296e7050672e:
      image_group_id: I0903
      title: ''
      base_file: v018.txt
    b156fdda926047a7a912f654f5661cfb:
      image_group_id: I0904
      title: ''
      base_file: v019.txt
    d625f1ed143041fb8a908d36e16a660a:
      image_group_id: I0905
      title: ''
      base_file: v020.txt
    716f829791f84b68a4475f2aa7fc37c9:
      image_group_id: I0906
      title: ''
      base_file: v021.txt
    bc396f230b4445b4b0e4aa758a39a1fa:
      image_group_id: I0907
      title: ''
      base_file: v022.txt
    af62e42a3db849da86eb819adfe95a3f:
      image_group_id: I0908
      title: ''
      base_file: v023.txt
    68f20989295b4ddcbf25e12fd92a982d:
      image_group_id: I0909
      title: ''
      base_file: v024.txt
    4369c69577414ffa893255c3c4898651:
      image_group_id: I0910
      title: ''
      base_file: v025.txt
    ef16f7a7239c4c53a8df791d06681d87:
      image_group_id: I0911
      title: ''
      base_file: v026.txt
    26cc84bb1a4747f583c26d716c430d77:
      image_group_id: I0912
      title: ''
      base_file: v027.txt
    10de35c22b854cefabfaabb17dd872b2:
      image_group_id: I0913
      title: ''
      base_file: v028.txt
    8617ae0dda2c475da68ada33722fca72:
      image_group_id: I0914
      title: ''
      base_file: v029.txt
    f6f1c72e073a497e8ec6224d8b4d8f7d:
      image_group_id: I0915
      title: ''
      base_file: v030.txt
    9877eb12f1054aeb827119a925de151b:
      image_group_id: I0916
      title: ''
      base_file: v031.txt
    e32c3b73064f41b4a08e6963afe00b4e:
      image_group_id: I0917
      title: ''
      base_file: v032.txt
    e7e0fb3a0fba475a8ea27b2dfb9af975:
      image_group_id: I0918
      title: ''
      base_file: v033.txt
    e19e565ccaf2446198179e07082463c7:
      image_group_id: I0919
      title: ''
      base_file: v034.txt
    2ece25dfcab1465ea9d0cc27fefcae96:
      image_group_id: I0920
      title: ''
      base_file: v035.txt
    362d153481464d058c41c2f79ad6c4b0:
      image_group_id: I0921
      title: ''
      base_file: v036.txt
    77d8b8ddd9f648ebbf10562936527500:
      image_group_id: I0922
      title: ''
      base_file: v037.txt
    7cc8b687d07040e19c53ffe433794259:
      image_group_id: I0923
      title: ''
      base_file: v038.txt
    bc5f67ea4f494fa1ad581402c2568af6:
      image_group_id: I0924
      title: ''
      base_file: v039.txt
    534a24ba50614f698c31faefa9782dec:
      image_group_id: I0925
      title: ''
      base_file: v040.txt
    5c340ea0b1f1446ba6f347912c7ca45b:
      image_group_id: I0926
      title: ''
      base_file: v041.txt
    0fd48e76fa6a44b1bcf6e74b9173789a:
      image_group_id: I0927
      title: ''
      base_file: v042.txt
    3d04075125654892af3ded3b9ff3fff5:
      image_group_id: I0928
      title: ''
      base_file: v043.txt
    9b58fa30ba24432788d1012302b68527:
      image_group_id: I0929
      title: ''
      base_file: v044.txt
    94f214b6a3cd4b1fbf43b439dcedf93a:
      image_group_id: I0930
      title: ''
      base_file: v045.txt
    2a441959cdff41ccb15fe8eb01d0db7e:
      image_group_id: I0931
      title: ''
      base_file: v046.txt
    968a0cb812e64963ab81f413a4cb09f2:
      image_group_id: I0932
      title: ''
      base_file: v047.txt
    964d2e659fc941e49b7d8d651005e41e:
      image_group_id: I0933
      title: ''
      base_file: v048.txt
    66f2e8a4b8e74c30be3ed943bbfd6feb:
      image_group_id: I0934
      title: ''
      base_file: v049.txt
    efc405a5596f4e618a2c428f4ed2ef4f:
      image_group_id: I0935
      title: ''
      base_file: v050.txt
    a1151f86e1994804bae28711b3ac22d9:
      image_group_id: I0936
      title: ''
      base_file: v051.txt
    97a781c027224cfa87f2d03a197a5ba6:
      image_group_id: I0937
      title: ''
      base_file: v052.txt
    e5da544da15f42e796f450bb77677aa7:
      image_group_id: I0938
      title: ''
      base_file: v053.txt
    0a71ad44e10a41f395e8e167e7deaeee:
      image_group_id: I0939
      title: ''
      base_file: v054.txt
    3f525ac5289b432dbd3ed529a51fe4fe:
      image_group_id: I0940
      title: ''
      base_file: v055.txt
    eb34a50350e64b33aa80fbab7d4632a4:
      image_group_id: I0941
      title: ''
      base_file: v056.txt
    611a331300d0476cbf0ad7ea0bcfd4f9:
      image_group_id: I0942
      title: ''
      base_file: v057.txt
    ac393f07a223495bbbce53cb4eeb141a:
      image_group_id: I0943
      title: ''
      base_file: v058.txt
    c8b157a8dfbd4a2fa6cafd9ab487b2e0:
      image_group_id: I0944
      title: ''
      base_file: v059.txt
    49995c9905d84abf8939f49aa0494dbd:
      image_group_id: I0945
      title: ''
      base_file: v060.txt
    77e82ab879d54450bceda5a0fcfa6213:
      image_group_id: I0946
      title: ''
      base_file: v061.txt
    238d4c4f98ab4fea912d3146a89187d4:
      image_group_id: I0947
      title: ''
      base_file: v062.txt
    7b0267d9baee4fe98f638df8fb063ce1:
      image_group_id: I0948
      title: ''
      base_file: v063.txt
    064f3f428a714641b5f4b0ef30265809:
      image_group_id: I0949
      title: ''
      base_file: v064.txt
    4c00b58e450d41d8aa0632919c6c32af:
      image_group_id: I0950
      title: ''
      base_file: v065.txt
    942fabb1c2c641ffa6279b98ef65fbbb:
      image_group_id: I0951
      title: ''
      base_file: v066.txt
    243777bc35e14659950ea633c7302c72:
      image_group_id: I0952
      title: ''
      base_file: v067.txt
    a997b67c5dea44d99cdd538897ae954f:
      image_group_id: I0953
      title: ''
      base_file: v068.txt
    3688c7ad666542aca21a785f11cb57f3:
      image_group_id: I0954
      title: ''
      base_file: v069.txt
    510860ccf25b4f9b822145de01bb8f84:
      image_group_id: I0955
      title: ''
      base_file: v070.txt
    7bfb612419d140119f8ab2d2d431c84c:
      image_group_id: I0956
      title: ''
      base_file: v071.txt
    4151ae0bd158456f8ab41327113f0c1f:
      image_group_id: I0957
      title: ''
      base_file: v072.txt
    7a6098a9fc5a44daa9235c527d772515:
      image_group_id: I0958
      title: ''
      base_file: v073.txt
    0f10033b2d9f477db67c83db5af83760:
      image_group_id: I0959
      title: ''
      base_file: v074.txt
    3ec668b895864311a030a92eb298f08f:
      image_group_id: I0960
      title: ''
      base_file: v075.txt
    58f0465692dd4f04a1fc13e9ca1c91c3:
      image_group_id: I0961
      title: ''
      base_file: v076.txt
    639617adf2f744589a86f86b51fd9a7d:
      image_group_id: I0962
      title: ''
      base_file: v077.txt
    c1b7ac8041544c10864dc01b204110a3:
      image_group_id: I0963
      title: ''
      base_file: v078.txt
    6b41b3074c384fd8805dc2aee046f6d5:
      image_group_id: I0964
      title: ''
      base_file: v079.txt
    727395ea3c5942dba64fce3597777a11:
      image_group_id: I0965
      title: ''
      base_file: v080.txt
    da1ad7fc4bc944ffa480e780c14b86c3:
      image_group_id: I0966
      title: ''
      base_file: v081.txt
    cca1127504b44252950fa0081dd0fcc3:
      image_group_id: I0967
      title: ''
      base_file: v082.txt
    5a6d39e74bef4136bfd60214210e73da:
      image_group_id: I0968
      title: ''
      base_file: v083.txt
    03653995234b45749eee41eb86eee913:
      image_group_id: I0969
      title: ''
      base_file: v084.txt
    20de7b24059145f8b9ff016865a3343a:
      image_group_id: I0970
      title: ''
      base_file: v085.txt
    c968da7e5e9b4137b5be41da40365bae:
      image_group_id: I0971
      title: ''
      base_file: v086.txt
    176456da747c4bd780c7440ee0f78ef3:
      image_group_id: I0972
      title: ''
      base_file: v087.txt
    937eabf892ae4c9ebe8db3d6768b445e:
      image_group_id: I0973
      title: ''
      base_file: v088.txt
    e90f6dbc3a8d4036893b680aa9d89b7d:
      image_group_id: I0974
      title: ''
      base_file: v089.txt
    da79be025e7d4f8da5ee752391ab5ca7:
      image_group_id: I0975
      title: ''
      base_file: v090.txt
    33099c8decd24d1ba57c616f7f7af3c9:
      image_group_id: I0976
      title: ''
      base_file: v091.txt
    f2b81d05f422417982034ba5088c6fe8:
      image_group_id: I0977
      title: ''
      base_file: v092.txt
    9844fe07623b4fb8a1b286bce9f9d088:
      image_group_id: I0978
      title: ''
      base_file: v093.txt
    dc61281a0dc542a4b04f15134eeb0ab6:
      image_group_id: I0979
      title: ''
      base_file: v094.txt
    d8b0eb1407d345b09ca4a1fe475bc1a6:
      image_group_id: I0980
      title: ''
      base_file: v095.txt
    088491d6021748d3b68a4b3e2ca9dc13:
      image_group_id: I0981
      title: ''
      base_file: v096.txt
    0f9ca0c84c294ff2877e7fd4309358b3:
      image_group_id: I0982
      title: ''
      base_file: v097.txt
    2145d299d75c49b89c280a8f58d4988d:
      image_group_id: I0983
      title: ''
      base_file: v098.txt
    0649dfe3cc144cab9a356bd02bf2c75f:
      image_group_id: I0984
      title: ''
      base_file: v099.txt
    e3d5deccc04949889d59919624e8698d:
      image_group_id: I0985
      title: ''
      base_file: v100.txt
    18688c1786894a36b044be6a25369eef:
      image_group_id: I0986
      title: ''
      base_file: v101.txt
    c82977b4bd81415fbf277385e9eb09cb:
      image_group_id: I0987
      title: ''
      base_file: v102.txt
    5bca148df3ba454fa4d53d9450128b87:
      image_group_id: I0988
      title: ''
      base_file: v103.txt
  author: ''
