id: I632E2418
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T00:25:40+00:00'
last_modified: '2022-06-16T07:33:05.312818+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22084
  title: བཀའ་འགྱུར ༼སྡེ་དགེ་པར་ཕུད༽
  author: ''
  base:
    '7475':
      image_group_id: I0886
      title: ''
      total_pages: ''
      order: 1
      base_file: 7475.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
